### PR TITLE
Milestone 2 part 7 work for team 4

### PR DESCRIPTION
**Pull request by nathanielburbank**
Hi Team 4, 

This pull request represents our (Team 2) work on part 7 for milestone 2. Everything seems to be in order from our perspective,and it seems to work well with your codebase. But let us know if you if you run into any problems or have any additional questions or concerns.

Thanks!
Nathaniel

### CODE REVIEW

**Comment by chinhuic** [comment]
Hi @nathanielburbank, thanks for making the pull request and for the work! However, merging directly into the Master branch is perhaps not the best practice. We would need you to close this request and fork our branch and pull to the branch instead. @erniechiew will reply here and let  you know the specific branch that you should merge on.

**Comment by erniechiew** [comment]
Hi @nathanielburbank. Thanks for your team's work! Please merge your work into the 'p7_work_from_team_2' branch of our repo. Let me know if you run into any problems.

**Comment by nathanielburbank** [comment]
I've switched the base from master to p7_work_from_team_2, so that if you accept the pull request, that is where the new code will end up. Let me know if this is not what you intended. 

Thanks!
Nathaniel

**Comment by nathanielburbank** [comment]
Also, it looks like you guys aren't loading portal locker or scipy in your travis config file. That should fix the reason the tests are failing.

**Comment by chinhuic** [comment]
Thanks @nathanielburbank! Appreciate your understanding.

**Pull request merged**
